#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🐶 Husky pre-commit hook triggered."
echo "🔍 Running lint to check code quality..."
pnpm run lint 

echo "Running format check"
pnpm run format:check

echo "Checking build success"
pnpm run build

echo "✅ Pre-commit All checks passed!"
echo "🚀 You're ready to commit clean, quality code!"
echo ""

